# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vilg(object):
    def setupUi(self, Vilg):
        Vilg.setObjectName("Vilg")
        Vilg.resize(281, 451)
        self.lineEdit = QtWidgets.QLineEdit(Vilg)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Vilg)
        self.pushButton.setGeometry(QtCore.QRect(220, 40, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Vilg)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Vilg)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Vilg)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 150, 81, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Vilg)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 261, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Vilg)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 260, 41, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 260, 211, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Vilg)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 221, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Vilg)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 370, 61, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 150, 51, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 150, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 370, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 370, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(Vilg)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 370, 71, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.line = QtWidgets.QFrame(Vilg)
        self.line.setGeometry(QtCore.QRect(10, 340, 261, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Vilg)
        self.line_2.setGeometry(QtCore.QRect(10, 230, 261, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Vilg)
        self.line_3.setGeometry(QtCore.QRect(10, 120, 261, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textBrowser = QtWidgets.QTextBrowser(Vilg)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 261, 41))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Vilg)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 180, 261, 41))
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Vilg)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 290, 261, 41))
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_3.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Vilg)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 400, 261, 41))
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_4.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_4.setObjectName("textBrowser_4")

        self.retranslateUi(Vilg)
        QtCore.QMetaObject.connectSlotsByName(Vilg)

    def retranslateUi(self, Vilg):
        _translate = QtCore.QCoreApplication.translate
        Vilg.setWindowTitle(_translate("Vilg", "Vilg"))
        self.pushButton.setText(_translate("Vilg", "Решить"))
        self.label.setText(_translate("Vilg", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Поменять min и max</span></p></body></html>"))
        self.label_2.setText(_translate("Vilg", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сравнить 3 числа</span></p><p><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("Vilg", "Сравнить"))
        self.label_3.setText(_translate("Vilg", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Найти уникальные записи</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Vilg", "Найти"))
        self.label_4.setText(_translate("Vilg", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Простой калькулятор</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Vilg", "Решить"))
        self.textBrowser.setHtml(_translate("Vilg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Vilg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Vilg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Vilg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
